services:
  - type: web
    name: datasync-backend
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_SHEETS_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: datasync-db
          property: connectionString

databases:
  - name: datasync-db
    region: ohio
    plan: free